import random
import re

random.seed(42)

# 36 small stars across 900x2000 (averaging ~4 on screen at any time)
stars1 = sorted([(random.randint(25, 875), random.randint(10, 1990)) for _ in range(36)])
# 16 medium stars (averaging ~2 on screen at any time)
stars2 = sorted([(random.randint(35, 865), random.randint(10, 1990)) for _ in range(16)])
# 8 bright stars (averaging ~1 on screen at any time)
stars3 = sorted([(random.randint(45, 855), random.randint(10, 1990)) for _ in range(8)])

with open(r'c:\Holidays\Arnim-Zola\assets\header.svg', 'r', encoding='utf-8') as f:
    old_svg = f.read()

font_match = re.search(r"@font-face\s*\{.*?src:\s*url\((data:font/woff2;.*?)\)\s*format\('woff2'\);.*?\}", old_svg, re.DOTALL)
font_src = font_match.group(1) if font_match else ''

svg_parts = []
svg_parts.append('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 240" width="100%" height="100%">')
svg_parts.append('  <defs>')
svg_parts.append('    <!-- Google Fonts: Caacupe One + JetBrains Mono -->')
svg_parts.append('    <style><![CDATA[')
svg_parts.append("      @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700;800&display=swap');")
svg_parts.append('')
svg_parts.append("      @font-face {")
svg_parts.append("        font-family: 'Caacupe One';")
svg_parts.append("        font-style: normal;")
svg_parts.append("        font-weight: 400;")
svg_parts.append(f"        src: url({font_src}) format('woff2');")
svg_parts.append("      }")
svg_parts.append('')
svg_parts.append("      .hero-title {")
svg_parts.append("        font-family: 'Caacupe One', cursive, sans-serif;")
svg_parts.append("        font-weight: 400;")
svg_parts.append("        letter-spacing: 3px;")
svg_parts.append("      }")
svg_parts.append("      .sub-title {")
svg_parts.append("        font-family: 'Caacupe One', cursive, sans-serif;")
svg_parts.append("        font-weight: 400;")
svg_parts.append("      }")
svg_parts.append("      .mono-text {")
svg_parts.append("        font-family: 'JetBrains Mono', 'Fira Code', 'Courier New', monospace;")
svg_parts.append("      }")
svg_parts.append('')
svg_parts.append("      /* Uiverse.io Parallax Starfield Drift Keyframes */")
svg_parts.append("      @keyframes driftStars1 {")
svg_parts.append("        from { transform: translateY(0px); }")
svg_parts.append("        to { transform: translateY(-2000px); }")
svg_parts.append("      }")
svg_parts.append("      @keyframes driftStars2 {")
svg_parts.append("        from { transform: translateY(0px); }")
svg_parts.append("        to { transform: translateY(-2000px); }")
svg_parts.append("      }")
svg_parts.append("      @keyframes driftStars3 {")
svg_parts.append("        from { transform: translateY(0px); }")
svg_parts.append("        to { transform: translateY(-2000px); }")
svg_parts.append("      }")
svg_parts.append('')
svg_parts.append("      .stars-layer1 {")
svg_parts.append("        animation: driftStars1 50s linear infinite;")
svg_parts.append("      }")
svg_parts.append("      .stars-layer2 {")
svg_parts.append("        animation: driftStars2 100s linear infinite;")
svg_parts.append("      }")
svg_parts.append("      .stars-layer3 {")
svg_parts.append("        animation: driftStars3 150s linear infinite;")
svg_parts.append("      }")
svg_parts.append('    ]]></style>')
svg_parts.append('')
svg_parts.append('    <!-- Uiverse.io Cosmic Emerald Gradient Background -->')
svg_parts.append('    <radialGradient id="uiverseEmeraldBg" cx="50%" cy="100%" r="90%" fx="50%" fy="100%">')
svg_parts.append('      <stop offset="0%" stop-color="#114a27" />')
svg_parts.append('      <stop offset="35%" stop-color="#082915" />')
svg_parts.append('      <stop offset="70%" stop-color="#04140a" />')
svg_parts.append('      <stop offset="100%" stop-color="#020704" />')
svg_parts.append('    </radialGradient>')
svg_parts.append('')
svg_parts.append('    <!-- Emerald Matrix Text Gradient Animation (Slower 8s Smooth Wave) -->')
svg_parts.append('    <linearGradient id="emeraldTextGrad" x1="-100%" y1="0%" x2="0%" y2="0%">')
svg_parts.append('      <stop offset="0%" stop-color="#39d353" />')
svg_parts.append('      <stop offset="25%" stop-color="#39d353" />')
svg_parts.append('      <stop offset="42%" stop-color="#7ee787" />')
svg_parts.append('      <stop offset="55%" stop-color="#ffffff" />')
svg_parts.append('      <stop offset="78%" stop-color="#ffffff" />')
svg_parts.append('      <stop offset="92%" stop-color="#7ee787" />')
svg_parts.append('      <stop offset="100%" stop-color="#39d353" />')
svg_parts.append('      <animate attributeName="x1" from="-100%" to="100%" dur="8s" repeatCount="indefinite" />')
svg_parts.append('      <animate attributeName="x2" from="0%" to="200%" dur="8s" repeatCount="indefinite" />')
svg_parts.append('    </linearGradient>')
svg_parts.append('')
svg_parts.append('    <!-- Horizontal Neon Green Divider Gradient -->')
svg_parts.append('    <linearGradient id="neonGreenLine" x1="0%" y1="0%" x2="100%" y2="0%">')
svg_parts.append('      <stop offset="0%" stop-color="#030604" stop-opacity="0" />')
svg_parts.append('      <stop offset="25%" stop-color="#238636" stop-opacity="0.6" />')
svg_parts.append('      <stop offset="50%" stop-color="#00ff66" stop-opacity="1" />')
svg_parts.append('      <stop offset="75%" stop-color="#238636" stop-opacity="0.6" />')
svg_parts.append('      <stop offset="100%" stop-color="#030604" stop-opacity="0" />')
svg_parts.append('    </linearGradient>')
svg_parts.append('')
svg_parts.append('    <!-- Rounded Corner Clip -->')
svg_parts.append('    <clipPath id="bannerClip">')
svg_parts.append('      <rect x="0" y="0" width="900" height="240" rx="14" />')
svg_parts.append('    </clipPath>')
svg_parts.append('  </defs>')
svg_parts.append('')
svg_parts.append('  <!-- ==================== MAIN BANNER CANVAS ==================== -->')
svg_parts.append('  <g clip-path="url(#bannerClip)">')
svg_parts.append('    <!-- 1. Background Base Card with Concentrated Emerald Glow -->')
svg_parts.append('    <rect x="0" y="0" width="900" height="240" fill="url(#uiverseEmeraldBg)" />')
svg_parts.append('')
svg_parts.append('    <!-- 2. Uiverse.io Parallax Starfield Layer 1 (Small Stars) -->')
svg_parts.append('    <g class="stars-layer1">')
for x, y in stars1:
    svg_parts.append(f'      <circle cx="{x}" cy="{y}" r="0.85" fill="#ffffff" opacity="0.85" />')
    svg_parts.append(f'      <circle cx="{x}" cy="{y + 2000}" r="0.85" fill="#ffffff" opacity="0.85" />')
svg_parts.append('    </g>')
svg_parts.append('')
svg_parts.append('    <!-- 3. Uiverse.io Parallax Starfield Layer 2 (Medium Stars) -->')
svg_parts.append('    <g class="stars-layer2">')
for x, y in stars2:
    svg_parts.append(f'      <circle cx="{x}" cy="{y}" r="1.3" fill="#ffffff" opacity="0.9" />')
    svg_parts.append(f'      <circle cx="{x}" cy="{y + 2000}" r="1.3" fill="#ffffff" opacity="0.9" />')
svg_parts.append('    </g>')
svg_parts.append('')
svg_parts.append('    <!-- 4. Uiverse.io Parallax Starfield Layer 3 (Bright Stars) -->')
svg_parts.append('    <g class="stars-layer3">')
for x, y in stars3:
    svg_parts.append(f'      <circle cx="{x}" cy="{y}" r="1.8" fill="#ffffff" opacity="1" />')
    svg_parts.append(f'      <circle cx="{x}" cy="{y + 2000}" r="1.8" fill="#ffffff" opacity="1" />')
svg_parts.append('    </g>')
svg_parts.append('')
svg_parts.append('    <!-- 5. Subtle Card Perimeter Border -->')
svg_parts.append('    <rect x="1" y="1" width="898" height="238" rx="13" fill="none" stroke="rgba(255,255,255,0.08)" stroke-width="1" />')
svg_parts.append('')
svg_parts.append('    <!-- 6. Centered Hero Typography Block -->')
svg_parts.append('    <g transform="translate(450, 0)">')
svg_parts.append('      <!-- TITLE: Mohammed Sahil (Dominant Hero Title in Caacupe One) -->')
svg_parts.append('      <g transform="translate(0, 90)">')
svg_parts.append('        <text x="0" y="0" text-anchor="middle" dominant-baseline="central" fill="url(#emeraldTextGrad)" font-size="68" class="hero-title">Mohammed Sahil</text>')
svg_parts.append('      </g>')
svg_parts.append('')
svg_parts.append('      <!-- Neon Accent Divider Line -->')
svg_parts.append('      <g transform="translate(0, 132)">')
svg_parts.append('        <line x1="-280" y1="0" x2="280" y2="0" stroke="url(#neonGreenLine)" stroke-width="1.8" />')
svg_parts.append('      </g>')
svg_parts.append('')
svg_parts.append('      <!-- Subtitle 1: Multimodal AI & Agentic Systems -->')
svg_parts.append('      <g transform="translate(0, 160)">')
svg_parts.append('        <text x="0" y="0" text-anchor="middle" dominant-baseline="central" fill="#7ee787" font-size="16.5" letter-spacing="1.5" class="sub-title">')
svg_parts.append('          Multimodal AI <tspan fill="#00ff66">•</tspan> Agentic RAG <tspan fill="#00ff66">•</tspan> Async Celery + Redis')
svg_parts.append('        </text>')
svg_parts.append('      </g>')
svg_parts.append('')
svg_parts.append('      <!-- Subtitle 2: 3D WebGL & Creative Frontend Stack -->')
svg_parts.append('      <g transform="translate(0, 187)">')
svg_parts.append('        <text x="0" y="0" text-anchor="middle" dominant-baseline="central" fill="#7ee787" font-size="16.5" letter-spacing="1.5" class="sub-title">')
svg_parts.append('          3D WebGL <tspan fill="#00ff66">•</tspan> GLSL Shaders <tspan fill="#00ff66">•</tspan> Next.js 16 <tspan fill="#00ff66">•</tspan> Bengaluru, IN')
svg_parts.append('        </text>')
svg_parts.append('      </g>')
svg_parts.append('    </g>')
svg_parts.append('  </g>')
svg_parts.append('</svg>')

content = '\n'.join(svg_parts)
with open(r'c:\Holidays\Arnim-Zola\assets\header-v2.svg', 'w', encoding='utf-8') as f:
    f.write(content)
with open(r'c:\Holidays\Arnim-Zola\assets\header.svg', 'w', encoding='utf-8') as f:
    f.write(content)

print(f'Generated minimal starfield: {len(stars1)} layer1, {len(stars2)} layer2, {len(stars3)} layer3.')
